---
- name: Test PokeAPI module
  hosts: localhost
  tasks:
          - name: Install my PokeAPI collection
            ansible.builtin.collection:
                    name: collections.pokeapi
                    state: present
          - name: Call pokeapi module
            pokeapi:
                    pokemon: "{{ pokemon_name }}"
            register: result

          - name: Print module result
            debug:
                    var: result
